### ISSUE TITLE
I got a SyntaxError when runing dataklasses.py

### ISSUE THREAD

**Issue by zhaoblake** [dabeaz/dataklasses#8]
exec(func(names), globals(), d := {}
SyntaxError: invalid syntax

My Python interpreter version is 3.72, is ":=" a new syntax featrue of later version?

**Comment by dabeaz** [comment]
:= is a feature of Python 3.8.

**Comment by zhaoblake** [comment]
> := is a feature of Python 3.8.

got it, many thanks!

**Comment by davidlatwe** [comment]
I have made my fork to work with Python 3.6+, if you're interested :)
https://github.com/davidlatwe/dataklasses
